### ISSUE TITLE
Not so much an issue as a request

### ISSUE THREAD

**Issue by WachoTheClown** [mad2342/DontShootTheDead#3]
I think it has been known for a long time that DontShootTheDead conflicts with something else in the Battletech Revised and Battletech Advanced mod collections. Any chance you can resolve that conflict? Someone indicated it was CAC and CAE mods that conflict. Thanks for the great mod.

**Comment by mad2342** [comment]
Sorry for the late reply, was off for a while.
To be honest, i don't care for the big modpacks and especially CAC is a mess to work with. So, to integrate DSTD the respective authors/teams are welcome to add it to their collections and make it work if they choose to.
Best regards, Mad
